GET http://localhost:3000/users

### Users
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":  "Nome Sobrenome",
  "email": "email3@email.com",
  "password": "abc123"
}
  "password": "abc123"
}