GET http://localhost:3000/users

### Users
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":  "Nome Sobrenome",
  "email": "email3@email.com",
  "password": "abc123"
}

### Partners
POST http://localhost:3000/partner/users
Content-Type: application/json

{
  "name":  "Nome Sobrenome",
  "email": "email4@email.com",
  "password": "abc123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "email4@email.com",
  "password": "123456"
}